### ISSUE TITLE
Android source code runs with errors and necessary files are missing

### ISSUE THREAD

**Issue by nemo-dsm** [ggerganov/ggwave-java#5]
xecution failed for task ':app:buildCMakeDebug[arm64-v8a]'.
> com.android.ide.common.process.ProcessException: ninja: Entering directory `C:\Users\y\Desktop\ggwave-java-master\app\.cxx\Debug\45019215\arm64-v8a'
  [1/2] Building CXX object CMakeFiles/test-cpp.dir/test-cpp.cpp.o
  [2/2] Linking CXX shared library C:\Users\y\Desktop\ggwave-java-master\app\build\intermediates\cxx\Debug\45019215\obj\arm64-v8a\libtest-cpp.so
  FAILED: C:/Users/y/Desktop/ggwave-java-master/app/build/intermediates/cxx/Debug/45019215/obj/arm64-v8a/libtest-cpp.so 
  cmd.exe /C "cd . && D:\Androidstudio\sdk\ndk\23.1.7779620\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=aarch64-none-linux-android21 --sysroot=D:/Androidstudio/sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/windows-x86_64/sysroot -fPIC -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fexceptions -frtti -stdlib=libc++ -g  -fno-limit-debug-info  -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--fatal-warnings -Qunused-arguments -Wl,--no-undefined -shared -Wl,-soname,libtest-cpp.so -o C:\Users\y\Desktop\ggwave-java-master\app\build\intermediates\cxx\Debug\45019215\obj\arm64-v8a\libtest-cpp.so CMakeFiles/test-cpp.dir/test-cpp.cpp.o  D:/Androidstudio/sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/lib/aarch64-linux-android/21/liblog.so   -static-libstdc++ -latomic -lm && cd ."
  ld: error: undefined symbol: ggwave_getDefaultParameters
  >>> referenced by test-cpp.cpp:18 (C:/Users/y/Desktop/ggwave-java-master/app/src/main/cpp\test-cpp.cpp:18)
  >>>               CMakeFiles/test-cpp.dir/test-cpp.cpp.o:(Java_com_album_gg_MainActivity_initNative)

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:buildCMakeDebug[arm64-v8a]'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:147)
	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:145)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:133)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:74)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:333)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:320)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:313)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:299)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$run$0(DefaultPlanExecutor.java:143)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:227)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:218)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:140)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
Caused by: org.gradle.internal.UncheckedException: com.android.ide.common.process.ProcessException: ninja: Entering directory `C:\Users\y\Desktop\ggwave-java-master\app\.cxx\Debug\45019215\arm64-v8a'
[1/2] Building CXX object CMakeFiles/test-cpp.dir/test-cpp.cpp.o
[2/2] Linking CXX shared library C:\Users\y\Desktop\ggwave-java-master\app\build\intermediates\cxx\Debug\45019215\obj\arm64-v8a\libtest-cpp.so
FAILED: C:/Users/y/Desktop/ggwave-java-master/app/build/intermediates/cxx/Debug/45019215/obj/arm64-v8a/libtest-cpp.so 
cmd.exe /C "cd . && D:\Androidstudio\sdk\ndk\23.1.7779620\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=aarch64-none-linux-android21 --sysroot=D:/Androidstudio/sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/windows-x86_64/sysroot -fPIC -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security -fexceptions -frtti -stdlib=libc++ -g  -fno-limit-debug-info  -Wl,--build-id=sha1 -Wl,--no-rosegment -Wl,--fatal-warnings -Qunused-arguments -Wl,--no-undefined -shared -Wl,-soname,libtest-cpp.so -o C:\Users\y\Desktop\ggwave-java-master\app\build\intermediates\cxx\Debug\45019215\obj\arm64-v8a\libtest-cpp.so CMakeFiles/test-cpp.dir/test-cpp.cpp.o  D:/Androidstudio/sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/windows-x86_64/sysroot/usr/lib/aarch64-linux-android/21/liblog.so   -static-libstdc++ -latomic -lm && cd ."
ld: error: undefined symbol: ggwave_getDefaultParameters
>>> referenced by test-cpp.cpp:18 (C:/Users/y/Desktop/ggwave-java-master/app/src/main/cpp\test-cpp.cpp:18)
>>>               CMakeFiles/test-cpp.dir/test-cpp.cpp.o:(Java_com_album_gg_MainActivity_initNative)

ld: error: undefined symbol: ggwave_init
>>> referenced by test-cpp.cpp:22 (C:/Users/y/Desktop/ggwave-java-master/app/src/main/cpp\test-cpp.cpp:22)
>>>               CMakeFiles/test-cpp.dir/test-cpp.cpp.o:(Java_com_album_gg_MainActivity_initNative)

ld: error: undefined symbol: ggwave_decode
>>> referenced by test-cpp.cpp:37 (C:/Users/y/Desktop/ggwave-java-master/app/src/main/cpp\test-cpp.cpp:37)
>>>               CMakeFiles/test-cpp.dir/test-cpp.cpp.o:(Java_com_album_gg_MainActivity_processCaptureData)

ld: error: undefined symbol: ggwave_encode
>>> referenced by test-cpp.cpp:57 (C:/Users/y/Desktop/ggwave-java-master/app/src/main/cpp\test-cpp.cpp:57)
>>>               CMakeFiles/test-cpp.dir/test-cpp.cpp.o:(Java_com_album_gg_MainActivity_sendMessage)
>>> referenced by test-cpp.cpp:61 (C:/Users/y/Desktop/ggwave-java-master/app/src/main/cpp\test-cpp.cpp:61)
>>>               CMakeFiles/test-cpp.dir/test-cpp.cpp.o:(Java_com_album_gg_MainActivity_sendMessage)
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

ggwave.h  The file already exists, and you can click to view the error.

**Comment by nemo-dsm** [comment]
Can you make a complete and runnable demo? The necessary .h files are missing.
